import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Providers from "./providers";
import { Button } from "@/components/shadcn/button";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"font-sans min-h-screen bg-background antialiased",
					inter.variable,
				)}
			>
				<Providers>
					<div className="md:mx-auto md:max-w-6xl w-screen py-2 px-8">
						<Button asChild>
							<Link href="/">Home</Link>
						</Button>
					</div>
					{children}
				</Providers>
			</body>
		</html>
	);
}
