import type { ShopFeed } from "@/graphql/bin/graphql";

export const hardcodedShopFeed: ShopFeed = {
  name: "shop",
  __typename: "ShopFeed",
  categories: [
    {
      name: "Home & Office",
      seeAllPath: "/au/shop/home-office",
      merchants: [
        {
          id: "7DfWYBDZ3gxVZQpvC3Zro0",
          title: "Amazon AU",
          image:
            "https://static-zip.imgix.net/store-assets/amazon-au-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/amazon-au-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/2eM1HqVoUVSW71T5hnQoKT/977cfb85f95eb70d474705518d95438d/amazon_logo_300x300.png",
          salesChannel: "Deal",
          headline: "6 mths interest free*",
          type: "Deal",
          href: "https://www.amazon.com.au/?tag=zip043-22&utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: "InterestFreePromo",
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Zip Money: Available to approved applicants only and subject to completion of satisfactory credit check upon application. Instalment plan splits eligible purchases of $300 and above into equal repayments within the interest free period. Eligible purchase excludes Zip bills and gift cards. A monthly account fee of $9.95 applies and a one off establishment fee may apply for new customers. Additional charges may apply, see T&Cs. Under the contract, minimum monthly repayments are required. If you turn off instalments, all future transactions will be reverted to the minimum monthly repayment. Paying only the minimum monthly repayment amount will generally not repay out the purchase within the interest free period. Any balance outstanding at the expiry of the interest free period will be charged at the applicable standard variable interest rate of 25.9% per annum, as at 1 June 2023. Interest, fees and charges are subject to change. Terms & Conditions apply and are available on application. See your contract for further details. Credit provided by ZipMoney Payments Pty Ltd (ABN 58 164 440 993, Australian Credit Licence Number 441878).",
            cashbackLimit: null,
            dealDescription: "6 Months interest free",
            cashbackId: "7DfWYBDZ3gxVZQpvC3Zro0",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "3Rhk99uJYGR0xY0pIxwp6Y",
          title: "eBay AU",
          image:
            "https://static-zip.imgix.net/store-assets/eBay-AU-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/eBay-AU-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/3AtRVyUk7tFssVWwKs3QD/88e22e9857a461f9a072a33300a17982/Ebay_300x300.png",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://ebay.us/8EiJmp",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "51845",
            cashbackId: "3Rhk99uJYGR0xY0pIxwp6Y",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "74XBL65XTqwVBLAE7PxwVb",
          title: "Bunnings Warehouse",
          image:
            "https://static-zip.imgix.net/store-assets/Bunnings-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/Bunnings-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/1GDS5w6udImWE3HVdS6tyu/cedb270fb1c905c730abcca5dfd8ba98/bunnings-warehouse-app-logo.jpg",
          salesChannel: "Deal",
          headline: "12 mths interest free*",
          type: "Deal",
          href: "https://www.bunnings.com.au/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: "InterestFreePromo",
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Zip Money: Available to approved applicants only and subject to completion of satisfactory credit check upon application. Instalment plan splits eligible purchases of $300 and above into equal repayments within the interest free period. Eligible purchase excludes Zip bills and gift cards. A monthly account fee of $9.95 applies and a one off establishment fee may apply for new customers. Additional charges may apply, see T&Cs. Under the contract, minimum monthly repayments are required. If you turn off instalments, all future transactions will be reverted to the minimum monthly repayment. Paying only the minimum monthly repayment amount will generally not repay out the purchase within the interest free period. Any balance outstanding at the expiry of the interest free period will be charged at the applicable standard variable interest rate of 25.9% per annum, as at 1 June 2023. Interest, fees and charges are subject to change. Terms & Conditions apply and are available on application. See your contract for further details. Credit provided by ZipMoney Payments Pty Ltd (ABN 58 164 440 993, Australian Credit Licence Number 441878).",
            cashbackLimit: null,
            dealDescription: "12 Months interest free. Minimum spend $2,000.",
            cashbackId: "74XBL65XTqwVBLAE7PxwVb",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "1uHScBztCPAsLTUYfB14l0",
          title: "JB Hi-Fi",
          image:
            "https://static-zip.imgix.net/store-assets/JB-HiFI-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/JB-HiFI-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/1b2TYoHXTPlU327pIfZMtm/d24a2b87f9cbf443541fe73dd6e22638/jbhifi-app-logo.jpg",
          salesChannel: "Deal",
          headline: "Tax Time Hot Deals!",
          type: "Deal",
          href: "https://www.jbhifi.com.au/pages/eofy-sale?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: "MerchantHosted",
            endDate: "2024-06-30T23:59",
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "*Offers made directly by retailer and subject to their T&Cs. See retailer website for more details. Zip does not guarantee the offer. Zip may receive a commission.",
            cashbackLimit: null,
            dealDescription:
              "Smash your tax time with the hottest deals on home entertainment, appliances and equipment.",
            cashbackId: "1uHScBztCPAsLTUYfB14l0",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "286fhNR5wfDlUTT47kKYEs",
          title: "Kmart Australia",
          image:
            "https://static-zip.imgix.net/store-assets/kmart-australia-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/kmart-australia-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/1KhyecftIQvkfdIaYZnfKp/6988232b2b6ef86e5eef673ea55b2b60/kmart-app-icon.png",
          salesChannel: "Deal",
          headline: "Clearance Sale",
          type: "Deal",
          href: "https://www.kmart.com.au/category/clearance/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: "MerchantHosted",
            endDate: "2024-06-30T23:59:59",
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "*Offers made directly by retailer and subject to their T&Cs. See retailer website for more details. Zip does not guarantee the offer. Zip may receive a commission.",
            cashbackLimit: null,
            dealDescription: "Huge clearance sale on now!",
            cashbackId: "286fhNR5wfDlUTT47kKYEs",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "6OkUX0OXc7JyULP9e9WW6S",
          title: "Catch",
          image:
            "https://static-zip.imgix.net/store-assets/catch-of-the-day-group-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/catch-of-the-day-group-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/2LutRLlWHRcWD1LVIbq551/4213f702b87b83ae9a2d99038e0413f5/Catch.jpg",
          salesChannel: "Online",
          headline: "2% cashback*",
          type: "Cashback",
          href: null,
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: 2,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Shop via the App using Zip's single-use card to earn 2% cashback per eligible transaction.\n Starts: 2022-03-26 12:00AM (AEST) Reward Program T&Cs apply.",
            cashbackLimit: null,
            dealDescription: "Catch Cashback",
            cashbackId: "6OkUX0OXc7JyULP9e9WW6S",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
      ],
      __typename: "Category",
    },
    {
      name: "Women's Fashion",
      seeAllPath: "/au/shop/womens-fashion",
      merchants: [
        {
          id: "67zQn7X2FeZfcBe4tmCRtm",
          title: "SHEIN",
          image:
            "https://static-zip.imgix.net/store-assets/shein-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/shein-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/1hWfMvhuG7GwJjtqsRVn4l/ecb75ec788a916d83f6cc10fc5a99e74/Shein-logo-300x300.jpg",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://au.shein.com/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "43092",
            cashbackId: "67zQn7X2FeZfcBe4tmCRtm",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "3YmH2t4w2nqwTsP9yQvh88",
          title: "Lovisa",
          image:
            "https://images.ctfassets.net/f49r9japosra/1Nu9kc4yeOBRclL6MOGkQ1/4ffcf461b437c59e0667a4c47753a3f8/Lovisa_Background_238KB.png",
          logo: "https://images.ctfassets.net/f49r9japosra/6AWdVSsqJzENlfflc9PV0G/5f75a860aedb2dc5a0ececeaa674bd3a/Lovisa_Logo.png",
          bubbleLogo: null,
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://www.lovisa.com.au/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "non-zip-lovisa",
            cashbackId: "3YmH2t4w2nqwTsP9yQvh88",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "4dHChp9UhpKMcZoyFkWP3t",
          title: "City Chic",
          image:
            "https://static-zip.imgix.net/store-assets/city-chic-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/city-chic-logo.png?w=160&h=200",
          bubbleLogo: null,
          salesChannel: "Online",
          headline: "3% cashback*",
          type: "Cashback",
          href: null,
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: 2,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Shop via the App using Zip's single-use card to earn 3% cashback per eligible transaction.\n Starts: 2021-11-01 12:00AM (AEST) Reward Program T&Cs apply.",
            cashbackLimit: null,
            dealDescription: "City Chic Cashback",
            cashbackId: "4dHChp9UhpKMcZoyFkWP3t",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "1cgWtDIVKyFvVNpGK8jr00",
          title: "Glassons",
          image:
            "https://images.ctfassets.net/f49r9japosra/3E86E2h71c0Cq2v3ftYxPz/654ab566e49dbc6dbc997220b698b190/glassons-background_1.png",
          logo: "https://images.ctfassets.net/f49r9japosra/tbHVHWTuUyUNnx84i18ZA/30a46f203df4a8264783e3e1ad78b23f/glassons-white.png",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/3p0Snwn0vvUGEmk8G1NHXE/188809af14368ba2a3ab2b1440e91557/Group_23.png",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://click.linksynergy.com/deeplink?id=xdc4Z/ZuaBU&mid=49260&murl=https%3A%2F%2Fwww.glassons.com%2F",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "non-zip-glassons",
            cashbackId: "1cgWtDIVKyFvVNpGK8jr00",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "3GTyGLsuM9PPAwF07llvj1",
          title: "Billy J Boutique",
          image:
            "https://static-zip.imgix.net/store-assets/Billy-J-Boutique-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/Billy-J-Boutique-logo.png?w=160&h=200",
          bubbleLogo: null,
          salesChannel: "Online and Instore",
          headline: null,
          type: "Merchant",
          href: "https://billyj.com.au/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "18642",
            cashbackId: "3GTyGLsuM9PPAwF07llvj1",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "6RvZUwkwIXCCppc9JkXNRq",
          title: "Seed Heritage",
          image:
            "https://static-zip.imgix.net/store-assets/Seed-Heritage-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/Seed-Heritage-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/G4LqCy3Tm6Nv5vyLhHa8N/4dc2ca5ed1c66cf1830fc7a1c6fc39ce/seed_logo.png",
          salesChannel: "Online",
          headline: "1% cashback*",
          type: "Cashback",
          href: null,
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: 2,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Shop via the App using Zip's single-use card to earn 1% cashback per eligible transaction.\n Starts: 2022-08-01 12:00AM (AEST) Reward Program T&Cs apply.",
            cashbackLimit: null,
            dealDescription: "Seed Heritage Cashback",
            cashbackId: "6RvZUwkwIXCCppc9JkXNRq",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
      ],
      __typename: "Category",
    },
    {
      name: "Electronics",
      seeAllPath: "/au/shop/electronics",
      merchants: [
        {
          id: "sZZFLjVcYZSQzG2PLMOeo",
          title: "Apple",
          image:
            "https://images.ctfassets.net/f49r9japosra/38Bj95kwktXHe3naTHTlLK/48668daad2a7b8f47f2c8b6b05a4b127/Apple_Background.png",
          logo: "https://images.ctfassets.net/f49r9japosra/2FUIXeUtPiGkio237baNgS/05f44168bf9457007055d618aa2354d8/Apple_logo_Zip.png",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/1lswWmgWtRHuEcbovEBfUq/5e412f79ed78d2dcd2d2010d58c38083/apple_logo.png",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://apple.sjv.io/c/2671251/435410/7643",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "non-zip-apple",
            cashbackId: "sZZFLjVcYZSQzG2PLMOeo",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "532HhIzlE9vF5f3fpPxDlY",
          title: "JB Hi-Fi",
          image:
            "https://static-zip.imgix.net/store-assets/JB-HiFI-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/JB-HiFI-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/1b2TYoHXTPlU327pIfZMtm/d24a2b87f9cbf443541fe73dd6e22638/jbhifi-app-logo.jpg",
          salesChannel: "Online and Instore",
          headline: null,
          type: "Merchant",
          href: "https://www.jbhifi.com.au/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "34980",
            cashbackId: "532HhIzlE9vF5f3fpPxDlY",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "7H16bwzwnP4EwfNjPr00D2",
          title: "Kogan.com",
          image:
            "https://static-zip.imgix.net/store-assets/kogancom-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/kogancom-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/23F0aXRDHbqF4fFyysWYsF/a8c2609db446ffed8d4704698131495b/Kogan_App.png",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://kogan.4p72pk.net/P0aVMR",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "7207",
            cashbackId: "7H16bwzwnP4EwfNjPr00D2",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "2dpxR3C4SFdQJ6wBQAijzY",
          title: "The Good Guys",
          image:
            "https://static-zip.imgix.net/store-assets/The-Good-Guys-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/The-Good-Guys-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/1Yur87scsDwEPJvTIVmGOg/27661f65819f20eb16adf88a5369b0fa/TGG-Logo__2_.png",
          salesChannel: "Online and Instore",
          headline: null,
          type: "Merchant",
          href: "https://prf.hn/click/camref:1100ljkQ3",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "34870",
            cashbackId: "2dpxR3C4SFdQJ6wBQAijzY",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "OiQuV4CfkSCCTa6Bc55Mt",
          title: "Amazon AU",
          image:
            "https://static-zip.imgix.net/store-assets/amazon-au-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/amazon-au-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/2eM1HqVoUVSW71T5hnQoKT/977cfb85f95eb70d474705518d95438d/amazon_logo_300x300.png",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "http://www.amazon.com.au/?tag=zip043-22",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "18298",
            cashbackId: "OiQuV4CfkSCCTa6Bc55Mt",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "5sa3yGavtL9RWEDdr5ZCZz",
          title: "Microsoft",
          image:
            "https://images.ctfassets.net/f49r9japosra/7KEN2UWVv9SxRvS2kGe48l/c7e241440fa96ce39f184b9778f6a67e/microsoft-background_1.png",
          logo: "https://images.ctfassets.net/f49r9japosra/1V4dfTFRFn5lq024vh4PRR/cfc1f5ed03f432c73c81aca3bb17d15b/enAU-Surface-ZIP-Microsoft-logo-ColourWhite.png",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/2RS1xsNSQay3yA6qLLqcHJ/a435be130dce6981c86bcaa1ecb82671/mircrosoft.png",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://click.linksynergy.com/deeplink?id=xdc4Z/ZuaBU&mid=42411&murl=https%3A%2F%2Fwww.microsoft.com%2Fen-au%2Fstore%2Fcollections%2Fmicrosoftsurfacedeals",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "non-zip-microsoft",
            cashbackId: "5sa3yGavtL9RWEDdr5ZCZz",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "70YvhYHCRUzdCdOZ9vF8at",
          title: "digiDirect",
          image:
            "https://static-zip.imgix.net/store-assets/digidirect-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/digidirect-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/2Q4w9CupoF13FxPRN7IzPs/388fcaf6e42c91d4b95982db7112b593/ST001_Zip-Frenzy-Merchant-Logo-Digi-Direct_001.jpg",
          salesChannel: "Online and Instore",
          headline: null,
          type: "Merchant",
          href: "https://www.digidirect.com.au/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "699",
            cashbackId: "70YvhYHCRUzdCdOZ9vF8at",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "64aM90uez8dlhtE6mCJYbM",
          title: "EB Games",
          image:
            "https://static-zip.imgix.net/store-assets/EB-Games-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/EB-Games-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/3hyrp0xQx99mhnjF1PnKnd/564002caa157ac74d9601a1f20d7aa6a/EBGames_logo_300x300.png",
          salesChannel: "Online and Instore",
          headline: null,
          type: "Merchant",
          href: "https://ebgames.com.au?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "13066",
            cashbackId: "64aM90uez8dlhtE6mCJYbM",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "1pCjgw4kyBgBuMoiz1ShEB",
          title: "Vodafone",
          image:
            "https://images.ctfassets.net/f49r9japosra/3x1GauQEfbTrZAlJjaxCzc/9bc5421223edd71cc812b863858a2ad5/vodafone-background.png",
          logo: "https://images.ctfassets.net/f49r9japosra/6PesPpyGUZY5VvjI4LzRIK/8f57e87c93b39a91ea1d61a8b1ae42bc/vodafone-logo.png",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/1fOXNpeFUlYGPWfvgExpq0/d03fc6cdfd0e1bace1b947107c4b8ee2/Vodafone-logo.gif",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://prf.hn/click/camref:1101liYp9/destination:https%3A%2F%2Fwww.vodafone.com.au%2Fhot-offers%3Ftitle%3Dprepaid",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "non-zip-vodafone",
            cashbackId: "1pCjgw4kyBgBuMoiz1ShEB",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "2CJNDrAc4SjnsS7b68rXtF",
          title: "JBL",
          image:
            "https://static-zip.imgix.net/store-assets/Ingram-JBL-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/Ingram-JBL-logo.png?w=160&h=200",
          bubbleLogo: null,
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://click.linksynergy.com/deeplink?id=xdc4Z/ZuaBU&mid=43240&murl=https%3A%2F%2Fwww.jbl.com.au%2F",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "23703",
            cashbackId: "2CJNDrAc4SjnsS7b68rXtF",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "3e5yzZNxeTIpvGbVCeXoxT",
          title: "BIG W",
          image:
            "https://static-zip.imgix.net/store-assets/big-w-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/big-w-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/9ibyJMaPnOYGmaqzzAvS9/059fa48eda9a9809b768cfe45e8e4cde/BIG_W.jpg",
          salesChannel: "Deal",
          headline: "6 mths interest free*",
          type: "Deal",
          href: "https://www.bigw.com.au/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: "InterestFreePromo",
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Zip Money: Available to approved applicants only and subject to completion of satisfactory credit check upon application. Instalment plan splits eligible purchases of $300 and above into equal repayments within the interest free period. Eligible purchase excludes Zip bills and gift cards. A monthly account fee of $9.95 applies and a one off establishment fee may apply for new customers. Additional charges may apply, see T&Cs. Under the contract, minimum monthly repayments are required. If you turn off instalments, all future transactions will be reverted to the minimum monthly repayment. Paying only the minimum monthly repayment amount will generally not repay out the purchase within the interest free period. Any balance outstanding at the expiry of the interest free period will be charged at the applicable standard variable interest rate of 25.9% per annum, as at 1 June 2023. Interest, fees and charges are subject to change. Terms & Conditions apply and are available on application. See your contract for further details. Credit provided by ZipMoney Payments Pty Ltd (ABN 58 164 440 993, Australian Credit Licence Number 441878).",
            cashbackLimit: null,
            dealDescription: "6 Months interest free. Minimum spend $100",
            cashbackId: "3e5yzZNxeTIpvGbVCeXoxT",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "37ZzaB9LT7xxFBrf2lZZip",
          title: "Telstra",
          image:
            "https://images.ctfassets.net/f49r9japosra/6CJ2nsrENQtFoe4XhwaVlC/8f9eee32ba7e975c766d401ff8f1ddc2/Telstra_Background_233KB.png",
          logo: "https://images.ctfassets.net/f49r9japosra/z6pdKcP4jJ7KGQ7QQo7HR/bfa9692dd39d568bda7d47321bce1776/Telstra_Logo.png",
          bubbleLogo: null,
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://www.telstra.com.au/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "non-zip-telstra",
            cashbackId: "37ZzaB9LT7xxFBrf2lZZip",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "3RROkgwH0xnOso7yIXM8K7",
          title: "Super Cheap Auto",
          image:
            "https://static-zip.imgix.net/store-assets/supercheap-auto-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/supercheap-auto-logo.png?w=160&h=200",
          bubbleLogo: null,
          salesChannel: "Deal",
          headline: "12 mths interest free*",
          type: "Deal",
          href: "https://www.supercheapauto.com.au/?utm_source=zip&utm_medium=referral&utm_campaign=au-sca-2020-zip#PR_On_Sale&utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: "InterestFreePromo",
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Zip Money: Available to approved applicants only and subject to completion of satisfactory credit check upon application. Instalment plan splits eligible purchases of $300 and above into equal repayments within the interest free period. Eligible purchase excludes Zip bills and gift cards. A monthly account fee of $9.95 applies and a one off establishment fee may apply for new customers. Additional charges may apply, see T&Cs. Under the contract, minimum monthly repayments are required. If you turn off instalments, all future transactions will be reverted to the minimum monthly repayment. Paying only the minimum monthly repayment amount will generally not repay out the purchase within the interest free period. Any balance outstanding at the expiry of the interest free period will be charged at the applicable standard variable interest rate of 25.9% per annum, as at 1 June 2023. Interest, fees and charges are subject to change. Terms & Conditions apply and are available on application. See your contract for further details. Credit provided by ZipMoney Payments Pty Ltd (ABN 58 164 440 993, Australian Credit Licence Number 441878).",
            cashbackLimit: null,
            dealDescription: "12 Months interest free. Minimum spend $1,500",
            cashbackId: "3RROkgwH0xnOso7yIXM8K7",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "hXOGHbTlHpyOd45ZJzKAh",
          title: "Apple",
          image:
            "https://images.ctfassets.net/f49r9japosra/38Bj95kwktXHe3naTHTlLK/48668daad2a7b8f47f2c8b6b05a4b127/Apple_Background.png",
          logo: "https://images.ctfassets.net/f49r9japosra/2FUIXeUtPiGkio237baNgS/05f44168bf9457007055d618aa2354d8/Apple_logo_Zip.png",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/1lswWmgWtRHuEcbovEBfUq/5e412f79ed78d2dcd2d2010d58c38083/apple_logo.png",
          salesChannel: "Online",
          headline: "1% cashback*",
          type: "Cashback",
          href: null,
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: 2,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Shop via the App using Zip's single-use card to earn 1% cashback per eligible transaction.\n Starts: 2023-06-07 08:00AM (AEST) Reward Program T&Cs apply.",
            cashbackLimit: null,
            dealDescription: "AFO :: Apple",
            cashbackId: "hXOGHbTlHpyOd45ZJzKAh",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "3kUwpc5KbiiZcUzMp3kKkR",
          title: "EB Games",
          image:
            "https://static-zip.imgix.net/store-assets/EB-Games-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/EB-Games-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/3hyrp0xQx99mhnjF1PnKnd/564002caa157ac74d9601a1f20d7aa6a/EBGames_logo_300x300.png",
          salesChannel: "Deal",
          headline: "6 mths interest free*",
          type: "Deal",
          href: "https://ebgames.com.au?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: "InterestFreePromo",
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Zip Money: Available to approved applicants only and subject to completion of satisfactory credit check upon application. Instalment plan splits eligible purchases of $300 and above into equal repayments within the interest free period. Eligible purchase excludes Zip bills and gift cards. A monthly account fee of $9.95 applies and a one off establishment fee may apply for new customers. Additional charges may apply, see T&Cs. Under the contract, minimum monthly repayments are required. If you turn off instalments, all future transactions will be reverted to the minimum monthly repayment. Paying only the minimum monthly repayment amount will generally not repay out the purchase within the interest free period. Any balance outstanding at the expiry of the interest free period will be charged at the applicable standard variable interest rate of 25.9% per annum, as at 1 June 2023. Interest, fees and charges are subject to change. Terms & Conditions apply and are available on application. See your contract for further details. Credit provided by ZipMoney Payments Pty Ltd (ABN 58 164 440 993, Australian Credit Licence Number 441878).",
            cashbackLimit: null,
            dealDescription: "6 Months interest free",
            cashbackId: "3kUwpc5KbiiZcUzMp3kKkR",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "3Rhk99uJYGR0xY0pIxwp6Y",
          title: "eBay AU",
          image:
            "https://static-zip.imgix.net/store-assets/eBay-AU-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/eBay-AU-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/3AtRVyUk7tFssVWwKs3QD/88e22e9857a461f9a072a33300a17982/Ebay_300x300.png",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://ebay.us/8EiJmp",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "51845",
            cashbackId: "3Rhk99uJYGR0xY0pIxwp6Y",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
      ],
      __typename: "Category",
    },
    {
      name: "Food & Drink",
      seeAllPath: "/au/shop/food-drink",
      merchants: [
        {
          id: "3MOKMsZNErxEcoZc7tX77q",
          title: "Woolworths",
          image:
            "https://images.ctfassets.net/f49r9japosra/1rqse0WM21cDyvkehsGeL4/b34c80a431df0b9e1dba1a0efdf34a54/Woolworths_Background_273KB.png",
          logo: "https://images.ctfassets.net/f49r9japosra/2bJMkDMtvr9AdtZ21AFZj2/b1950e6c3936ea1701f10ded6f2a6266/Woolworths_Logo.png",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/6bZxDY18FSHsYKHqggZAtp/817e91f8446bf21e9a1b6764ba3c616d/woolworths-app-logo.png",
          salesChannel: "Deal",
          headline: "Jump into fresher and healthier food",
          type: "Deal",
          href: "https://supermarkets.4emhls.net/P0d2aj",
          integrated: false,
          offer: {
            dealType: "MerchantHosted",
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "*Offers made directly by retailer and subject to their T&Cs. See retailer website for more details. Zip does not guarantee the offer. Zip may receive a commission.",
            cashbackLimit: null,
            dealDescription: "Woolworths ",
            cashbackId: "3MOKMsZNErxEcoZc7tX77q",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "59LzV4iXI9QgvbtTX6S3T6",
          title: "Coles",
          image:
            "https://images.ctfassets.net/f49r9japosra/1VCwZr1HKuEvX9eRzATjzm/08536f2d5d04ee3790ca853808edcb20/Coles_Background_220KB.png",
          logo: "https://images.ctfassets.net/f49r9japosra/4QBW5oBNsO4tNaFwbyCAkw/248af00743afdf792cf7b25b414040c6/ColesLogo.png",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/2hnRtPZ1VExprZBa20VqEA/7b7031c899bedc1facd04a92cfaafa5c/coles-app-icon.png",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://www.coles.com.au?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "non-zip-coles",
            cashbackId: "59LzV4iXI9QgvbtTX6S3T6",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "1SN8LWNTzVjXucJHCfewFS",
          title: "McDonald's",
          image:
            "https://images.ctfassets.net/f49r9japosra/3Zlaez3ULSFO8H6E5oo7T9/eebd324b23ac9e8123241d48f3e99894/McDonald-s_Background_174KB.png",
          logo: "https://images.ctfassets.net/f49r9japosra/2xyftbSZhmr5Ho7TZnjR0h/c0228f9f27b2325a22fa26abd4342dfc/McDonald-s_Logo.png",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/3O1VDHylo5OCxXubjD0dG9/f123aaad8e1b915980182383b5ec6c85/McDonalds.png",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://mcdonalds.com.au/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "non-zip-mcdonalds",
            cashbackId: "1SN8LWNTzVjXucJHCfewFS",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "2Cff87MlAByzqQ3IDzd0Bl",
          title: "KFC",
          image:
            "https://images.ctfassets.net/f49r9japosra/3607NTIGbJsIBAoowy8mgz/bdcf312ca7327b8488546bb78e91ee77/KFC_Background_191KB.png",
          logo: "https://images.ctfassets.net/f49r9japosra/2CW7MahxmKcjDWES7alV2u/1908236846cfba42555bedd9b59cfc69/KFC_Logo.png",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/dz3ggjvQUuYp8Nu91wsX5/c0693448dfaa0b3ed18b88970c5a050f/App_icons_mask.png",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://www.kfc.com.au/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "non-zip-kfc",
            cashbackId: "2Cff87MlAByzqQ3IDzd0Bl",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "4h2EvdXAQEJCt9F88UOYDb",
          title: "BWS",
          image:
            "https://images.ctfassets.net/f49r9japosra/1Xdso1Frg0FljpIFays2f3/d772f29328dcd2534d955b5977e07771/BWS_Background.png",
          logo: "https://images.ctfassets.net/f49r9japosra/4K59HlOGEO5eDKsB9XV6LE/5bf6a9b879e49aa941052207cf6ddbdf/BWS_Logo.png",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/5Ckxhjs9D6Z9Uzum6vOrS8/981ef043a857ded540f1790814058496/bws_app_logo.png",
          salesChannel: "Online",
          headline: "2% cashback*",
          type: "Cashback",
          href: null,
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: 2,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Shop via the App using Zip's single-use card to earn 2% cashback per eligible transaction.\n Starts: 2023-03-06 12:00AM (AEST) Reward Program T&Cs apply.",
            cashbackLimit: null,
            dealDescription: "BWS Cashback",
            cashbackId: "4h2EvdXAQEJCt9F88UOYDb",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "5k9NEOeh0y4npyTQKJGE37",
          title: "Uber Eats",
          image:
            "https://images.ctfassets.net/f49r9japosra/2Q1fChsBEZSHlUtpZn2Djc/25f13c04e58ce47d05f251abe6440bc2/Uber_Eats_Background_220KB.png",
          logo: "https://images.ctfassets.net/f49r9japosra/1Y6xVyLyAFZGulCWdbsmJi/41d83310d05f81927b7ac2557e362805/Uber_Eats_Logo.png",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/2EkZau32maqXCxQAz8k1BT/a395fdb8146abdc92c81ee6923d2842a/UE_Logo_Vertical_RGB_web_GreenBG.png",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://ubertrk.com/c/2671251/1125665/5714",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "non-zip-uber-eats",
            cashbackId: "5k9NEOeh0y4npyTQKJGE37",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
      ],
      __typename: "Category",
    },
    {
      name: "Sports & Recreation",
      seeAllPath: "/au/shop/sports-recreation",
      merchants: [
        {
          id: "6UII3wrgV1TJFTWnYVEtf",
          title: "Rebel Sport",
          image:
            "https://static-zip.imgix.net/store-assets/Rebel-Sport-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/Rebel-Sport-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/5GKx8VlMszVcI4MSPMqTMX/c300588bfab5cb65297ef99b1b9487af/Rebel_logo_300x300.png",
          salesChannel: "Deal",
          headline: "12 mths interest free*",
          type: "Deal",
          href: "https://www.rebelsport.com.au/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: "InterestFreePromo",
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Zip Money: Available to approved applicants only and subject to completion of satisfactory credit check upon application. Instalment plan splits eligible purchases of $300 and above into equal repayments within the interest free period. Eligible purchase excludes Zip bills and gift cards. A monthly account fee of $9.95 applies and a one off establishment fee may apply for new customers. Additional charges may apply, see T&Cs. Under the contract, minimum monthly repayments are required. If you turn off instalments, all future transactions will be reverted to the minimum monthly repayment. Paying only the minimum monthly repayment amount will generally not repay out the purchase within the interest free period. Any balance outstanding at the expiry of the interest free period will be charged at the applicable standard variable interest rate of 25.9% per annum, as at 1 June 2023. Interest, fees and charges are subject to change. Terms & Conditions apply and are available on application. See your contract for further details. Credit provided by ZipMoney Payments Pty Ltd (ABN 58 164 440 993, Australian Credit Licence Number 441878).",
            cashbackLimit: null,
            dealDescription: "12 Months interest free. Minimum spend $1,500",
            cashbackId: "6UII3wrgV1TJFTWnYVEtf",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "2WpbFIb8xYZpi3v8ASv7ep",
          title: "Anaconda",
          image:
            "https://static-zip.imgix.net/store-assets/anaconda-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/anaconda-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/jUwADpYLFtV18L15FxxvQ/413752d9eff289fcd83d450e57e745fb/anaconda-app-icon.png",
          salesChannel: "Deal",
          headline: "12 mths interest free*",
          type: "Deal",
          href: "https://www.anacondastores.com?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: "InterestFreePromo",
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Zip Money: Available to approved applicants only and subject to completion of satisfactory credit check upon application. Instalment plan splits eligible purchases of $300 and above into equal repayments within the interest free period. Eligible purchase excludes Zip bills and gift cards. A monthly account fee of $9.95 applies and a one off establishment fee may apply for new customers. Additional charges may apply, see T&Cs. Under the contract, minimum monthly repayments are required. If you turn off instalments, all future transactions will be reverted to the minimum monthly repayment. Paying only the minimum monthly repayment amount will generally not repay out the purchase within the interest free period. Any balance outstanding at the expiry of the interest free period will be charged at the applicable standard variable interest rate of 25.9% per annum, as at 1 June 2023. Interest, fees and charges are subject to change. Terms & Conditions apply and are available on application. See your contract for further details. Credit provided by ZipMoney Payments Pty Ltd (ABN 58 164 440 993, Australian Credit Licence Number 441878).",
            cashbackLimit: null,
            dealDescription: "12 Months interest free. Minimum spend $1,000",
            cashbackId: "2WpbFIb8xYZpi3v8ASv7ep",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "48U2bzjlPluhZAgkXmUMVl",
          title: "BCF",
          image:
            "https://static-zip.imgix.net/store-assets/bcf-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/bcf-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/1JC2iJO2xRfIJm6OKuXPFv/2cb3e325e7fd3d3d1e5835d7ee4a36fa/bcf-app-icon.png",
          salesChannel: "Online",
          headline: "2% cashback*",
          type: "Cashback",
          href: null,
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: 2,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Shop via the App using Zip's single-use card to earn 2% cashback per eligible transaction.\n Starts: 2023-06-07 12:00AM (AEST) Reward Program T&Cs apply.",
            cashbackLimit: null,
            dealDescription: "AFO :: BCF",
            cashbackId: "48U2bzjlPluhZAgkXmUMVl",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "2Pi5ITOA9JPJPhx5xM9cx1",
          title: "4wd Supacentre",
          image:
            "https://images.ctfassets.net/f49r9japosra/4kms5drxDEjTFSvnCWZqa0/8396fd715053aa30aaf75648159925a8/2024-05-20T04_49_40.934702475Z-CAMPING.jpg",
          logo: "https://static-zip.imgix.net/store-assets/4wd-supacentre-logo.png?w=160&h=200",
          bubbleLogo: null,
          salesChannel: "Deal",
          headline: "Up to 50% off*",
          type: "Deal",
          href: "https://www.4wdsupacentre.com.au/specials/daily-specials.html?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: "MerchantHosted",
            endDate: "2024-06-30T23:59:59",
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "*Offers made directly by retailer and subject to their T&Cs. See retailer website for more details. Zip does not guarantee the offer. Zip may receive a commission.",
            cashbackLimit: null,
            dealDescription: "Daily deals and massive clearance sale.",
            cashbackId: "2Pi5ITOA9JPJPhx5xM9cx1",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "B1oZVedftOrNscyUNejjZ",
          title: "Repco",
          image:
            "https://static-zip.imgix.net/store-assets/repco-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/repco-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/77B95Bly6MinxQen4ZTXKG/9016084d16eadadd73a1600256b45ab0/App_icons_mask__4_.png",
          salesChannel: "Deal",
          headline: "6 mths interest free*",
          type: "Deal",
          href: "http://www.repco.com.au/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: "InterestFreePromo",
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Zip Money: Available to approved applicants only and subject to completion of satisfactory credit check upon application. Instalment plan splits eligible purchases of $300 and above into equal repayments within the interest free period. Eligible purchase excludes Zip bills and gift cards. A monthly account fee of $9.95 applies and a one off establishment fee may apply for new customers. Additional charges may apply, see T&Cs. Under the contract, minimum monthly repayments are required. If you turn off instalments, all future transactions will be reverted to the minimum monthly repayment. Paying only the minimum monthly repayment amount will generally not repay out the purchase within the interest free period. Any balance outstanding at the expiry of the interest free period will be charged at the applicable standard variable interest rate of 25.9% per annum, as at 1 June 2023. Interest, fees and charges are subject to change. Terms & Conditions apply and are available on application. See your contract for further details. Credit provided by ZipMoney Payments Pty Ltd (ABN 58 164 440 993, Australian Credit Licence Number 441878).",
            cashbackLimit: null,
            dealDescription: "6 Months interest free",
            cashbackId: "B1oZVedftOrNscyUNejjZ",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "4Z4Um17GLDNQV04NJmqaYw",
          title: "Peloton",
          image:
            "https://static-zip.imgix.net/store-assets/Peloton-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/Peloton-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/1UV3SlQfbHUjXt6zE9IV7M/830350c939ba0e41ec471022f0d0be6d/Peloton_App_logo_300x300.png",
          salesChannel: "Deal",
          headline: "43 mths interest free",
          type: "Deal",
          href: "https://www.onepeloton.com.au/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: "InterestFreePromo",
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Zip Money: Available to approved applicants only and subject to completion of satisfactory credit check upon application. Instalment plan splits eligible purchases of $300 and above into equal repayments within the interest free period. Eligible purchase excludes Zip bills and gift cards. A monthly account fee of $9.95 applies and a one off establishment fee may apply for new customers. Additional charges may apply, see T&Cs. Under the contract, minimum monthly repayments are required. If you turn off instalments, all future transactions will be reverted to the minimum monthly repayment. Paying only the minimum monthly repayment amount will generally not repay out the purchase within the interest free period. Any balance outstanding at the expiry of the interest free period will be charged at the applicable standard variable interest rate of 25.9% per annum, as at 1 June 2023. Interest, fees and charges are subject to change. Terms & Conditions apply and are available on application. See your contract for further details. Credit provided by ZipMoney Payments Pty Ltd (ABN 58 164 440 993, Australian Credit Licence Number 441878).",
            cashbackLimit: null,
            dealDescription:
              "43 months interest free when you purchase a Peloton Bike, Bike+ or Tread with Zip Money. ",
            cashbackId: "4Z4Um17GLDNQV04NJmqaYw",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
      ],
      __typename: "Category",
    },
    {
      name: "Men's Fashion",
      seeAllPath: "/au/shop/mens-fashion",
      merchants: [
        {
          id: "6yyoxhID5zxP18pCSk4dD7",
          title: "Cotton On",
          image:
            "https://static-zip.imgix.net/store-assets/Cotton-On-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/Cotton-On-logo.png?w=160&h=200",
          bubbleLogo: null,
          salesChannel: "Online",
          headline: "6% cashback*",
          type: "Cashback",
          href: null,
          integrated: true,
          offer: {
            dealType: null,
            endDate: "2024-06-07T23:59",
            activationExpiry: 2,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Shop via the App using Zip's single-use card to earn 6% cashback per eligible transaction.\n Starts: 2024-05-27 12:00AM (AEST) Ends: 2024-06-07 11:59PM (AEST) Reward Program T&Cs apply.",
            cashbackLimit: null,
            dealDescription: "AFO :: Cotton On :: May 27 - Jun 7",
            cashbackId: "6yyoxhID5zxP18pCSk4dD7",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "EFB7xnKSk4fwsNtbNxZKT",
          title: "City Beach",
          image:
            "https://static-zip.imgix.net/store-assets/city-beach-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/city-beach-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/25qGVSYEmM8g8Q3ujErq7p/eb8427329c654139df076447ed1bfb43/CityBeach_logo_300x300__1_.png",
          salesChannel: "Online",
          headline: "4% cashback*",
          type: "Cashback",
          href: null,
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: 2,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Shop via the App using Zip's single-use card to earn 4% cashback per eligible transaction.\n Starts: 2021-11-17 12:00AM (AEST) Reward Program T&Cs apply.",
            cashbackLimit: null,
            dealDescription: "City Beach Cashback",
            cashbackId: "EFB7xnKSk4fwsNtbNxZKT",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "77liSWnauawDqHWVOF154j",
          title: "Best & Less",
          image:
            "https://static-zip.imgix.net/store-assets/best-less-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/best-less-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/BST2h7R4svTHoLQLE6szm/a516e051e09a04f62f2800b2a35c666d/Best_and_Less_logo.png",
          salesChannel: "Online",
          headline: "2% cashback*",
          type: "Cashback",
          href: null,
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: 2,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Shop via the App using Zip's single-use card to earn 2% cashback per eligible transaction.\n Starts: 2021-11-01 12:00AM (AEST) Reward Program T&Cs apply.",
            cashbackLimit: null,
            dealDescription: "Best & Less Cashback",
            cashbackId: "77liSWnauawDqHWVOF154j",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "12iFPY9uo1SMpYX485Yr7R",
          title: "THE ICONIC",
          image:
            "https://images.ctfassets.net/f49r9japosra/6wVuQLhJrDWv1zHFZqaopW/897bf79655afdde8582de953fc2639da/800x640.png",
          logo: "https://images.ctfassets.net/f49r9japosra/41Yo8AjKKcfDtgPD3xVnS/ce828be4944179412bf596a7815f1bda/The_Iconic_Logo.png",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/6uEXIjRROFdQvwqmGUw8KJ/f9ff88e9bebd5d4396d19bc5088f6b1a/appiconic-app-logo.png",
          salesChannel: "Online",
          headline: "4% cashback*",
          type: "Cashback",
          href: null,
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: 2,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Shop via the App using Zip's single-use card to earn 4% cashback per eligible transaction.\n Starts: 2023-08-02 12:00AM (AEST) Reward Program T&Cs apply.",
            cashbackLimit: null,
            dealDescription: "AFO :: THE ICONIC",
            cashbackId: "12iFPY9uo1SMpYX485Yr7R",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "629j4qy80ejJutEzF9agca",
          title: "Platypus Shoes",
          image:
            "https://images.ctfassets.net/f49r9japosra/2L7nGRKcHbN1lsSkCACTLn/ee30544a9a9b77c63578f187c5bbf21b/Platypus_Background_168KB.png",
          logo: "https://images.ctfassets.net/f49r9japosra/5YoGSVNfy4xojAKqve6VjK/0e0c4bc59a45e5c358b60f85f6da94e7/Platypus_Logo.png",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/5I1avHaHIE6pZ97EUjokEs/db28a708b957cf2cd07880f593954d1a/Platypus.png",
          salesChannel: "Online",
          headline: "4% cashback*",
          type: "Cashback",
          href: null,
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: 2,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions:
              "Shop via the App using Zip's single-use card to earn 4% cashback per eligible transaction.\n Starts: 2021-11-01 12:00AM (AEST) Reward Program T&Cs apply.",
            cashbackLimit: null,
            dealDescription: "Platypus Shoes Cashback",
            cashbackId: "629j4qy80ejJutEzF9agca",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "5q4urYP7rnEn210Vq6RCWU",
          title: "Zara",
          image:
            "https://images.ctfassets.net/f49r9japosra/7k6qbHI9O0GOzWHO8V7FzV/986fdea0f376b30c4a621b156b49c426/Zara_Background_200KB.png",
          logo: "https://images.ctfassets.net/f49r9japosra/U2ke6gQs6VWKCA4hfwA2b/c05b1d2eefc0c5bdb7359fce5dc86454/Zara_Logo.png",
          bubbleLogo: null,
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://www.zara.com/au/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "non-zip-zara",
            cashbackId: "5q4urYP7rnEn210Vq6RCWU",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
      ],
      __typename: "Category",
    },
    {
      name: "Top Gift Cards",
      seeAllPath: null,
      merchants: [
        {
          id: "4jbtKV91mOu6PSj3j5wYSU",
          title: "7/11 Visa Digital Gift Card Store Card Gift Card",
          image:
            "https://images.ctfassets.net/f49r9japosra/6KotTWVkhrQ40k1L9F6jnm/5e04fda15c8b8085dff7673b72ed714b/gc-aubhnavsc001",
          logo: null,
          bubbleLogo: null,
          salesChannel: null,
          headline: null,
          type: "GiftCard",
          href: "https://zip.co/au/giftcards/checkout/AUBHNAVSC001",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "7/11 Visa Digital Gift Card Store Card",
            cashbackId: "4jbtKV91mOu6PSj3j5wYSU",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "zgBGNaDF6adwCFT0xMfsh",
          title: "Zip Anything Gift Card",
          image:
            "https://images.ctfassets.net/f49r9japosra/4a7UOkZDn97Jt40ZOCbrkL/4c8fe15fb8cd4bd1d61e91e576d081a0/gc-zip_anything_smart_card_aud_24",
          logo: null,
          bubbleLogo: null,
          salesChannel: null,
          headline: null,
          type: "GiftCard",
          href: "https://zip.co/au/giftcards/checkout/ZIP_ANYTHING_SMART_CARD_AUD_24",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "Zip Anything",
            cashbackId: "zgBGNaDF6adwCFT0xMfsh",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "6ANNX8WkX7niwhTc1NTgaz",
          title: "Ticketmaster Gift Card",
          image:
            "https://images.ctfassets.net/f49r9japosra/1sFs3NtBO90xgQ1cLaX2cN/f447ab3e9fd381b9a34182a3d61dd9a1/gc-ticketmaster",
          logo: null,
          bubbleLogo: null,
          salesChannel: null,
          headline: null,
          type: "GiftCard",
          href: "https://zip.co/au/giftcards/checkout/TICKETMASTER",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "Ticketmaster",
            cashbackId: "6ANNX8WkX7niwhTc1NTgaz",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "5ou4hlOGHbFrKMDITpmy9E",
          title: "Airbnb Store Card Gift Card",
          image:
            "https://images.ctfassets.net/f49r9japosra/1h4FJi9r1q9BTVV2i5SwzK/83af8da4287bcf0f6630c7c4801e7d12/gc-aubhnanbc001",
          logo: null,
          bubbleLogo: null,
          salesChannel: null,
          headline: null,
          type: "GiftCard",
          href: "https://zip.co/au/giftcards/checkout/AUBHNANBC001",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "Airbnb Store Card",
            cashbackId: "5ou4hlOGHbFrKMDITpmy9E",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "71cCEXfcuh9bprvYqR9Ytv",
          title: "Amazon.com.au Gift Card",
          image:
            "https://images.ctfassets.net/f49r9japosra/01buZnjkraE73wRtyrkDIz/300e3e89c304503980661c72deb5a0be/gc-amazon",
          logo: null,
          bubbleLogo: null,
          salesChannel: null,
          headline: null,
          type: "GiftCard",
          href: "https://zip.co/au/giftcards/checkout/AMAZON",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "Amazon.com.au",
            cashbackId: "71cCEXfcuh9bprvYqR9Ytv",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "ieNaVwaxKMcQdO4rqbE8s",
          title: "Restaurant Choice Store Card Gift Card",
          image:
            "https://images.ctfassets.net/f49r9japosra/2EyXx2GIHmh7bGDhE30Yol/a8c4f6bf6015790b38bee74fc330bdba/gc-aubhnrcbc001",
          logo: null,
          bubbleLogo: null,
          salesChannel: null,
          headline: null,
          type: "GiftCard",
          href: "https://zip.co/au/giftcards/checkout/AUBHNRCBC001",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "Restaurant Choice Store Card",
            cashbackId: "ieNaVwaxKMcQdO4rqbE8s",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "43pRKFQnlph0PUp5931MAt",
          title: "Woolworths Gift Card",
          image:
            "https://images.ctfassets.net/f49r9japosra/ObpPAvCFR1wqjb8jMfhKP/1a014647c13112e4a69d18f8a8be3680/gc-woolworths_new",
          logo: null,
          bubbleLogo: null,
          salesChannel: null,
          headline: null,
          type: "GiftCard",
          href: "https://zip.co/au/giftcards/checkout/WOOLWORTHS_NEW",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "Woolworths",
            cashbackId: "43pRKFQnlph0PUp5931MAt",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
      ],
      __typename: "Category",
    },
    {
      name: "Zip's Picks",
      seeAllPath: null,
      merchants: [
        {
          id: "3Rhk99uJYGR0xY0pIxwp6Y",
          title: "eBay AU",
          image:
            "https://static-zip.imgix.net/store-assets/eBay-AU-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/eBay-AU-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/3AtRVyUk7tFssVWwKs3QD/88e22e9857a461f9a072a33300a17982/Ebay_300x300.png",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://ebay.us/8EiJmp",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "51845",
            cashbackId: "3Rhk99uJYGR0xY0pIxwp6Y",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "1QynrzeuX5EUc1tEcGmz67",
          title: "Coco Republic",
          image:
            "https://static-zip.imgix.net/store-assets/coco-republic-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/coco-republic-logo.png?w=160&h=200",
          bubbleLogo: null,
          salesChannel: "Online and Instore",
          headline: null,
          type: "Merchant",
          href: "http://www.cocorepublic.com.au?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "549",
            cashbackId: "1QynrzeuX5EUc1tEcGmz67",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "01zDqXA86kbKCvOwUCb1SW",
          title: "Super Cheap Auto",
          image:
            "https://static-zip.imgix.net/store-assets/supercheap-auto-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/supercheap-auto-logo.png?w=160&h=200",
          bubbleLogo: null,
          salesChannel: "Online and Instore",
          headline: null,
          type: "Merchant",
          href: "https://www.supercheapauto.com.au/?utm_source=zip&utm_medium=referral&utm_campaign=au-sca-2020-zip#PR_On_Sale&utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "10796",
            cashbackId: "01zDqXA86kbKCvOwUCb1SW",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "32iUKhKiiKo9KS9cUTl4FK",
          title: "Dyson",
          image:
            "https://static-zip.imgix.net/store-assets/dyson-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/dyson-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/2vxU1vLaBpCspLWDyCKpT2/887747592167d269b258f6495d4ad8a1/Dyson_logo_300x300.png",
          salesChannel: "Online and Instore",
          headline: null,
          type: "Merchant",
          href: "https://click.linksynergy.com/deeplink?id=xdc4Z/ZuaBU&mid=43020&murl=https%3A%2F%2Fwww.dyson.com.au%2F",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "9515",
            cashbackId: "32iUKhKiiKo9KS9cUTl4FK",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "11QEtW0M9uzMqLfcrCwXZH",
          title: "Expedia",
          image:
            "https://images.ctfassets.net/f49r9japosra/7ovVd7VwIMswMRN2XnC6d5/7289e649963ee244b25aab2312d782d5/Expedia_AdobeStock_273464066.jpeg",
          logo: null,
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/6ntONBIzm6rdSBHWA6J3ll/6888cc3176d6bf49755b49aa022cd556/expediav2.jpeg",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://prf.hn/click/camref:1011loyJH/destination:https://www.expedia.com.au/",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "non-zip-expedia",
            cashbackId: "11QEtW0M9uzMqLfcrCwXZH",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "6zWqzNixwgNbnA88oLGWCp",
          title: "Sir the Label",
          image: null,
          logo: null,
          bubbleLogo: null,
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://sirthelabel.com/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "58146",
            cashbackId: "6zWqzNixwgNbnA88oLGWCp",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "5R4AKF3NZgMhQByrrFFQO5",
          title: "Stayz",
          image:
            "https://images.ctfassets.net/f49r9japosra/1mIklcwCiWWnR9f4loslA1/e78205c8cedb756d4850fb1c825bafc0/Stayz_Image.jpg",
          logo: "https://images.ctfassets.net/f49r9japosra/32EAUVTCwkow13iWT78vpF/c31a69c6f3362f39a92204beef3aa4b1/800x640-2.png",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/7i0bkHnu3BwufNiaoaiBzq/e41235d66b6a60ad9624c3593c14d7a0/stayz-app-icon.png",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://prf.hn/click/camref:1100lovWm",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "non-zip-stayz",
            cashbackId: "5R4AKF3NZgMhQByrrFFQO5",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "6iZlAJT9mV0fLFmprRGwh",
          title: "Qantas",
          image:
            "https://static-zip.imgix.net/store-assets/qantas-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/qantas-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/698XHYBpiuAgs4ewKudb7R/a6fdb19af48a0687ed5cb1c2d4295526/Qantas_Logo.png",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://book.qantas.com/?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "47891",
            cashbackId: "6iZlAJT9mV0fLFmprRGwh",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "2A9ap0aprDj950g22jpH1x",
          title: "DoorDash",
          image:
            "https://images.ctfassets.net/f49r9japosra/3ARgvJwLGy24iJXskppSew/c21d1714558bad237cd9cca5e43b9371/DoorDash_Background_265KB.png",
          logo: null,
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/4oKbbRYvXxhHY4t5Nss4R0/3d660f9396fa2e092b18fbfc487f18c0/dash.jpg",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://www.doordash.com?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: false,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "non-zip-doordash",
            cashbackId: "2A9ap0aprDj950g22jpH1x",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
        {
          id: "24L9tslV3VygJDUeIIp7Zj",
          title: "Jetstar",
          image:
            "https://static-zip.imgix.net/store-assets/Jetstar-background.png?w=320&h=400",
          logo: "https://static-zip.imgix.net/store-assets/Jetstar-logo.png?w=160&h=200",
          bubbleLogo:
            "https://images.ctfassets.net/f49r9japosra/JPbygO4AQDHWlexa7VMwH/a39339cd62515bfde4154e1661844305/Jetstar-logo-300x300.png",
          salesChannel: "Online",
          headline: null,
          type: "Merchant",
          href: "https://www.jetstar.com/au/en/home?utm_source=zip&utm_medium=referral&utm_campaign=WebFeed",
          integrated: true,
          offer: {
            dealType: null,
            endDate: null,
            activationExpiry: null,
            promoCode: null,
            additionalTerms: null,
            termsAndConditions: null,
            cashbackLimit: null,
            dealDescription: "49919",
            cashbackId: "24L9tslV3VygJDUeIIp7Zj",
            __typename: "MerchantOffer",
          },
          __typename: "Merchant",
        },
      ],
      __typename: "Category",
    },
  ],
};
